// Try Catch

try {
    console.log("First");
    console.log(x);
    console.log("Last");
} catch (error) {
    console.log("Error....");
    console.log(error);
    
}